[WIP] Add TSB manifest files for OLM-based operator deployment
openshift/template-service-broker-operator pull request #12
Opened 2018-12-17 22:35 UTC by djwhatle

See https://github.com/openshift/ansible-service-broker/pull/1151

2018-12-17 23:43 UTC, djwhatle commented
Unable to generate a Subscription and get the operator running with these manifest files, will troubleshoot tomorrow

2018-12-18 21:55 UTC, djwhatle commented on manifests/04-tsb-subscription.yaml
> +  startingCSV: templateservicebrokeroperator.v0.1.0
Fixed this issue from yesterday... a simple typo.

2018-12-18 21:56 UTC, djwhatle commented
Fixed the issue from yesterday, was a small typo in the Subscription yaml. Ready for review and merge!

2018-12-19 13:52 UTC, djzager requested changes
Probably have some changes we should make for ASB based on this feedback also. My belief is that the closer we are now to what they want in 4.0, the easier life will be when it comes to get everything fully integrated.

2018-12-19 13:52 UTC, djzager commented on manifests/03-tsb-operatorgroup.yaml
> +metadata:
do we need the operator running in the TSB namespace?

2018-12-19 13:52 UTC, djzager commented on manifests/01-tsb-catalogsource-configmap.yaml
> +                        valueFrom:
I think if we make this `value: openshift-template-service-broker` then we would be able to create the TSB operator where they want it (`rh-operators`) and just deploy the broker where it belongs.

2018-12-19 15:25 UTC, djwhatle commented on manifests/03-tsb-operatorgroup.yaml
> +metadata:
I haven't tried running it from elsewhere yet, but we can look at getting the operator into the shared operator namespace. Have you tried what you're mentioning?

2018-12-19 15:26 UTC, djwhatle commented on manifests/01-tsb-catalogsource-configmap.yaml
> +                        valueFrom:
Let's give it a shot today. I agree it would be good to get our operators into the desired shared namespace if technically possible.

2018-12-19 17:57 UTC, djzager commented on manifests/03-tsb-operatorgroup.yaml
> +metadata:
:sunglasses: Will try this afternoon.

2018-12-21 03:56 UTC, djzager commented
With your excellent introduction of https://github.com/fusor/catbrokers4 I don't think this PR is needed anymore. I don't want these files to live in multiple places and get stale.

2019-01-10 02:09 UTC, closed without merging